/**
 * Honest schema.org `dateModified` — the date the CONTENT last changed, not
 * the date the site was last built.
 *
 * Templates previously used `const BUILD_DATE = new Date().toISOString()`, so
 * every page asserted it had been modified TODAY on every deploy. Measured
 * 2026-09-06: `src/data/palettes.ts` had not changed since 2026-04-10, so the
 * 378 palette pages had been overstating their freshness by ~5 months, daily.
 * schema.org defines dateModified as "the date on which the CreativeWork was
 * most recently modified" — so that was a false claim, and `bot-harvest.md`
 * names the pattern ("freshness lie") as an anti-pattern.
 *
 * Dates come from `src/data/content-dates.json`, regenerated by
 * `node scripts/gen-content-dates.mjs` (git commit date per source file) and
 * committed. Precomputed rather than read from git at build time because this
 * repo's CI can run on a shallow clone, where `git log` returns empty and the
 * natural fallback is a clock — reinstating the anti-pattern invisibly.
 *
 * A page's content changes when EITHER its template or its data changes, so
 * pass both and take the later of the two.
 */
import dates from "@data/content-dates.json";

const MAP = dates as Record<string, string>;

export function contentDate(...paths: string[]): string {
  const found = paths.map((p) => MAP[p]).filter(Boolean);
  if (found.length === 0) {
    // Refuse rather than fall back to a clock — falling back is the bug.
    throw new Error(
      `contentDate: no entry for ${paths.join(", ")} in content-dates.json. ` +
        `Add the path to scripts/gen-content-dates.mjs and re-run it.`,
    );
  }
  return found.sort()[found.length - 1];
}
