/**
 * Honest schema.org `dateModified` — the date the CONTENT last changed, not
 * the date the site was last built.
 *
 * Templates previously used `const BUILD_DATE = new Date().toISOString()`, so
 * every page asserted it had been modified TODAY on every deploy. Measured
 * 2026-09-06: `src/data/palettes.ts` had not changed since 2026-04-10, so the
 * 378 palette pages had been overstating their freshness by ~5 months, daily.
 * schema.org defines dateModified as "the date on which the CreativeWork was
 * most recently modified" — so that was a false claim, and `bot-harvest.md`
 * names the pattern ("freshness lie") as an anti-pattern.
 *
 * Dates come from `src/data/content-dates.json`, regenerated by
 * `node scripts/gen-content-dates.mjs` (git commit date per source file) and
 * committed. Precomputed rather than read from git at build time because this
 * repo's CI can run on a shallow clone, where `git log` returns empty and the
 * natural fallback is a clock — reinstating the anti-pattern invisibly.
 *
 * A page's content changes when EITHER its template or its data changes, so
 * pass both and take the later of the two.
 *
 * KNOWN AND ACCEPTED LIMITATION — do not "fix" this without reading on.
 * Because we take the MAX, a purely cosmetic edit to a template (a CSS tweak,
 * a font-loading change) moves that page's date even though its data did not
 * change. Seen live 2026-09-06: /data/sanzo-wada-color-analysis/ renders
 * "Last verified 2026-09-06" while src/data/wada-palettes.ts has been
 * unchanged since 2026-04-10.
 *
 * That is deliberate, for two reasons:
 *   1. For schema.org `dateModified` the max is CORRECT. The spec asks when
 *      the CreativeWork was modified, and a template edit does modify the
 *      page. Reporting the older data date there would be the inaccurate one.
 *   2. Taking the data date instead would UNDERSTATE a build that genuinely
 *      re-derived and re-asserted every number from source.
 *
 * The residual imprecision is only in the user-facing "Last verified" string,
 * which reuses `modified`. If that ever needs to be exact, the fix is to add a
 * SECOND value (data-paths only) and render that — not to change the max()
 * here, which would regress `dateModified` on every page.
 */
import dates from "@data/content-dates.json";

const MAP = dates as Record<string, string>;

export function contentDate(...paths: string[]): string {
  const found = paths.map((p) => MAP[p]).filter(Boolean);
  if (found.length === 0) {
    // Refuse rather than fall back to a clock — falling back is the bug.
    throw new Error(
      `contentDate: no entry for ${paths.join(", ")} in content-dates.json. ` +
        `Add the path to scripts/gen-content-dates.mjs and re-run it.`,
    );
  }
  return found.sort()[found.length - 1];
}
