#!/usr/bin/env node
/**
 * make-worker.mjs — generate dist/_worker.js from the three Pages Functions.
 *
 * WHY THIS EXISTS. Pages "advanced mode" (_worker.js) and Pages Functions
 * (functions/) are mutually exclusive delivery mechanisms for the SAME code:
 *   • wrangler pages deploy  COMPILES functions/ — but EPIPEs at ~56MB.
 *   • chunked direct upload  handles any size — but ships STATIC ASSETS ONLY
 *     and cannot compile a Function.
 * dist/ is ~92MB, so every deploy takes the chunked path and the Functions are
 * silently dropped. That is why /go/p/* and /go/b/* returned 404 in production
 * on 2026-08-28 while the site itself served 200 — every Amazon buy link dead.
 * fitmylens hit the identical failure on 2026-08-26 and fixed it the same way
 * (see programmatic/fitmylens-com/scripts/make-worker.mjs, commit ddd9fca8).
 *
 * ⚠️ THE COLORCOMBINATIONS-SPECIFIC CONSTRAINT. functions/go/b/[[isbn]].js
 * warns that "adding a _worker.js here would disable functions/api/subscribe.js".
 * That is true and it is why this generator merges ALL THREE handlers rather
 * than only the gate. Dropping /api/subscribe would silently kill the email
 * capture — the fleet's compounding asset.
 *
 * GENERATED, never hand-written: a hand-copied second copy of the gate is a
 * drift bug waiting to happen (token window, ASIN regex, tag and EU routing
 * would diverge, and only one copy actually serves). functions/ stays the
 * single source of truth; this only adds the _worker.js entrypoint around it.
 *
 * ⚠️ _worker.js takes over ALL routing. Anything not matched MUST fall through
 * to env.ASSETS.fetch(request) or the whole site 404s. The try/catch is
 * load-bearing for the same reason: any throw falls back to ASSETS, so a bug in
 * the gate can degrade the buy path but can never take the site down.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";

const OUT = "dist/_worker.js";
const SRC = {
  book: "functions/go/b/[[isbn]].js",
  product: "functions/go/p/[[asin]].js",
  subscribe: "functions/api/subscribe.js",
};

for (const [k, p] of Object.entries(SRC)) {
  if (!existsSync(p)) { console.error(`make-worker: ${p} missing (${k})`); process.exit(1); }
}

// Rename each module's exported handler to a unique local name. Refuse to emit
// if a rename does not apply — an unrenamed duplicate `onRequestGet` is a
// redeclaration SyntaxError that would take the entire site down.
const rename = (file, pairs) => {
  let s = readFileSync(file, "utf8");
  for (const [from, to] of pairs) {
    if (!s.includes(from)) {
      console.error(`make-worker: expected \`${from}\` in ${file} — refusing to emit`);
      process.exit(1);
    }
    s = s.replace(from, to);
  }
  if (/^\s*export /m.test(s)) {
    console.error(`make-worker: an unrenamed \`export\` survives in ${file} — refusing to emit`);
    process.exit(1);
  }
  return s;
};

const book = rename(SRC.book, [["export const onRequestGet", "const goBook"]]);
const product = rename(SRC.product, [["export const onRequestGet", "const goProduct"]]);
const subscribe = rename(SRC.subscribe, [
  ["export async function onRequestPost", "async function apiSubscribePost"],
  ["export async function onRequestGet", "async function apiSubscribeGet"],
]);

writeFileSync(OUT, `// GENERATED by scripts/make-worker.mjs — DO NOT EDIT.
// Sources: ${SRC.book} · ${SRC.product} · ${SRC.subscribe}
// Edit the Function; regenerate this. Two hand-maintained copies WILL drift,
// and only one of them is the one actually serving.

${book}

${product}

${subscribe}

export default {
  async fetch(request, env, ctx) {
    try {
      const p = new URL(request.url).pathname;
      const ctxObj = { request, env, ctx };

      // /go/b/* — books (ISBN-10, EU geo-routed)
      if (p === "/go/b" || p.startsWith("/go/b/")) return await goBook(ctxObj);
      // /go/p/* — products (B-prefix ASINs, .com only)
      if (p === "/go/p" || p.startsWith("/go/p/")) return await goProduct(ctxObj);
      // Any other /go/* shape → home. Never a 404 dead-end on a money path.
      if (p === "/go" || p.startsWith("/go/")) {
        return Response.redirect(new URL(request.url).origin + "/", 302);
      }

      // /api/subscribe — the email capture. Dropping this is the exact failure
      // functions/go/b/[[isbn]].js warned about.
      if (p === "/api/subscribe" || p === "/api/subscribe/") {
        if (request.method === "POST") return await apiSubscribePost(ctxObj);
        return await apiSubscribeGet(ctxObj);
      }

      // Everything else is a static asset. Failing to pass it through would
      // 404 the whole site.
      return await env.ASSETS.fetch(request);
    } catch (e) {
      // Never let a handler bug become a site outage.
      try { return await env.ASSETS.fetch(request); }
      catch { return new Response("Service temporarily unavailable", { status: 503 }); }
    }
  },
};
`);
console.log(`make-worker: ${OUT} written (${readFileSync(OUT).length} bytes)`);
