import type { PaintingPalette } from "@/types/painting";

/**
 * Colour palettes sampled from public-domain paintings.
 *
 * HOW THIS FILE IS MADE — see /paintings/methodology for the reader-facing
 * version. Images come from Wikimedia Commons and are used only where the
 * licence resolves to public domain and the artist is independently confirmed
 * in the file metadata. Swatches are extracted by k-means clustering in
 * CIELAB, then snapped to the nearest real pixel, so every hex published here
 * is a colour that actually occurs on the canvas rather than an average of
 * two colours that appears nowhere on it.
 *
 * Pigment claims and `shift` notes appear ONLY where published conservation
 * research supports them, and each carries its sources. Entries without that
 * research carry no pigment claims — the palette structure is described
 * instead, because that much is observable from the swatches themselves.
 *
 * Generated by scripts/gen-paintings.mjs. Hand-written notes live in that
 * script; re-running regenerates this file.
 */
export const paintingPalettes: PaintingPalette[] = [
  {
    "slug": "the-starry-night",
    "title": "The Starry Night",
    "artist": "Vincent van Gogh",
    "year": "1889",
    "museum": "Museum of Modern Art, New York",
    "summary": "Three blues, one chrome yellow, and a near-black — the tightest famous palette in Western painting.",
    "story": [
      "The scheme is a textbook complementary pair pushed to its limit: a deep blue field interrupted by yellow at maximum separation on the colour wheel. What the extraction shows that reproductions often flatten is how dark the darkest note really is, and how little yellow there actually is by area. The stars feel enormous; they occupy very little canvas.",
      "This is the clearest case in the collection for weighting a palette by intensity rather than coverage. Sample this painting by area alone and the yellow disappears entirely, leaving six blues and a scheme that is accurate to the surface and wrong about the picture."
    ],
    "pigments": [],
    "shift": null,
    "sources": [],
    "colors": [
      {
        "hex": "#B19E2D",
        "share": 0.0096,
        "role": "accent",
        "chroma": 58.1,
        "lightness": 65
      },
      {
        "hex": "#5272A1",
        "share": 0.0638,
        "role": "ground",
        "chroma": 28.9,
        "lightness": 47.5
      },
      {
        "hex": "#344B91",
        "share": 0.0399,
        "role": "accent",
        "chroma": 43.9,
        "lightness": 33.6
      },
      {
        "hex": "#28378D",
        "share": 0.0285,
        "role": "accent",
        "chroma": 55.3,
        "lightness": 27
      },
      {
        "hex": "#272822",
        "share": 0.0646,
        "role": "ground",
        "chroma": 4.2,
        "lightness": 15.8
      },
      {
        "hex": "#151919",
        "share": 0.0828,
        "role": "ground",
        "chroma": 2,
        "lightness": 8.3
      }
    ],
    "image": {
      "commonsFile": "File:Van Gogh - Starry Night - Google Art Project.jpg",
      "commonsPage": "https://commons.wikimedia.org/wiki/File:Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg",
      "license": "Public domain"
    }
  },
  {
    "slug": "the-bedroom",
    "title": "The Bedroom",
    "artist": "Vincent van Gogh",
    "year": "1889",
    "museum": "Art Institute of Chicago",
    "summary": "A 6-colour reading of The Bedroom, sampled from the canvas itself.",
    "story": [
      "This palette runs from #A3AA99 at its lightest to #712B11 at its darkest, with 3 accent notes carrying most of the chromatic interest. The three largest areas of the painting set the base; the accents are the colours that give the work its character without necessarily covering much of it.",
      "Every swatch is a colour that genuinely occurs on the surface — each one is snapped to the nearest real pixel rather than averaged, so nothing here is a colour the painter never actually put down."
    ],
    "pigments": [],
    "shift": null,
    "sources": [],
    "colors": [
      {
        "hex": "#A3AA99",
        "share": 0.0811,
        "role": "ground",
        "chroma": 9.7,
        "lightness": 68.6
      },
      {
        "hex": "#8C9C9E",
        "share": 0.0897,
        "role": "ground",
        "chroma": 6,
        "lightness": 63.2
      },
      {
        "hex": "#A88F14",
        "share": 0.0317,
        "role": "accent",
        "chroma": 60.8,
        "lightness": 59.9
      },
      {
        "hex": "#A2810C",
        "share": 0.0807,
        "role": "ground",
        "chroma": 58.7,
        "lightness": 55.5
      },
      {
        "hex": "#997610",
        "share": 0.0593,
        "role": "accent",
        "chroma": 54.6,
        "lightness": 51.6
      },
      {
        "hex": "#712B11",
        "share": 0.0128,
        "role": "accent",
        "chroma": 43,
        "lightness": 27.5
      }
    ],
    "image": {
      "commonsFile": "File:Vincent van Gogh - De slaapkamer - Google Art Project.jpg",
      "commonsPage": "https://commons.wikimedia.org/wiki/File:Vincent_van_Gogh_-_De_slaapkamer_-_Google_Art_Project.jpg",
      "license": "Public domain"
    }
  },
  {
    "slug": "sunflowers",
    "title": "Sunflowers",
    "artist": "Vincent van Gogh",
    "year": "1888",
    "museum": "National Gallery, London",
    "summary": "Six yellows and almost nothing else — a painting that dares you to build a palette out of one hue.",
    "story": [
      "Van Gogh wrote to his brother Theo about painting \"nothing but sunflowers\", and the palette shows the ambition literally: this is a near-monochrome built from yellow alone, separated only by value and by how much green or brown each mixture carries. There is no complementary violet to make the yellow sing. The yellow has to do all the work by itself.",
      "That is why the palette is unusually hard to use in design and unusually instructive to study. Take the full ramp and you get a scheme with real warmth but no contrast anchor; add a single dark neutral and the whole thing snaps into focus. It is the clearest argument in this collection for value contrast doing the job people usually assign to hue contrast."
    ],
    "pigments": [
      {
        "name": "Chrome yellow (lead chromate, PbCrO₄)",
        "note": "The bright body of the flowers. Van Gogh used several varieties, including a sulfur-rich lemon form."
      },
      {
        "name": "Chrome yellow, sulfate-rich variety (PbCr₁₋ₓSₓO₄)",
        "note": "The pale lemon tones. This is the unstable one."
      }
    ],
    "shift": "Measurably. Synchrotron study of the Van Gogh Museum canvas found the sulfate-rich chrome yellows undergoing photo-induced reduction, with roughly 35% of surface chromium converted from Cr(VI) to Cr(III) — the chemistry that turns pale yellow toward olive brown. Researchers note the change is not yet obvious to the naked eye, so the swatches here are close to, but very slightly browner than, what left the studio in 1888.",
    "sources": [
      {
        "label": "Monico et al., Angewandte Chemie Int. Ed. (2015) — degradation of chrome yellows in Sunflowers",
        "href": "https://onlinelibrary.wiley.com/doi/abs/10.1002/anie.201505840"
      },
      {
        "label": "ESRF — Van Gogh's Sunflowers: evidence of chrome yellow degradation",
        "href": "https://www.esrf.fr/home/UsersAndScience/Publications/Highlights/highlights-2015/x-ray-nanoprobe/xnp08.html"
      }
    ],
    "colors": [
      {
        "hex": "#F2E986",
        "share": 0.091,
        "role": "ground",
        "chroma": 50.1,
        "lightness": 91.2
      },
      {
        "hex": "#E2D876",
        "share": 0.0836,
        "role": "ground",
        "chroma": 50.1,
        "lightness": 85.3
      },
      {
        "hex": "#BDA719",
        "share": 0.0635,
        "role": "accent",
        "chroma": 67.5,
        "lightness": 68.4
      },
      {
        "hex": "#B19D1B",
        "share": 0.1035,
        "role": "ground",
        "chroma": 63.5,
        "lightness": 64.6
      },
      {
        "hex": "#B2921A",
        "share": 0.023,
        "role": "accent",
        "chroma": 61.2,
        "lightness": 61.7
      },
      {
        "hex": "#9D7D11",
        "share": 0.0566,
        "role": "accent",
        "chroma": 56.2,
        "lightness": 53.9
      }
    ],
    "image": {
      "commonsFile": "File:Vincent Willem van Gogh 127.jpg",
      "commonsPage": "https://commons.wikimedia.org/wiki/File:Vincent_Willem_van_Gogh_127.jpg",
      "license": "Public domain"
    }
  },
  {
    "slug": "cafe-terrace-at-night",
    "title": "Café Terrace at Night",
    "artist": "Vincent van Gogh",
    "year": "1888",
    "museum": "Kröller-Müller Museum",
    "summary": "Gaslight gold against night blue — van Gogh's complementary scheme at its most legible.",
    "story": [
      "This is the same blue-and-yellow opposition as The Starry Night, but resolved far more comfortably: the gold occupies much more of the surface, so the contrast reads as warmth rather than tension. The orange and olive notes sit between the two poles and stop the pair from feeling merely graphic.",
      "Van Gogh wrote about painting the night without using black, and the palette bears that out — the darkest swatches here are deep blue-greys rather than true neutrals."
    ],
    "pigments": [],
    "shift": null,
    "sources": [],
    "colors": [
      {
        "hex": "#DBCA45",
        "share": 0.0297,
        "role": "accent",
        "chroma": 66,
        "lightness": 80.6
      },
      {
        "hex": "#C8B547",
        "share": 0.0575,
        "role": "ground",
        "chroma": 57,
        "lightness": 73.4
      },
      {
        "hex": "#6F80A9",
        "share": 0.0568,
        "role": "accent",
        "chroma": 24.1,
        "lightness": 53.7
      },
      {
        "hex": "#AD662A",
        "share": 0.0367,
        "role": "accent",
        "chroma": 50.4,
        "lightness": 50.2
      },
      {
        "hex": "#403E43",
        "share": 0.0615,
        "role": "ground",
        "chroma": 3.4,
        "lightness": 26.6
      },
      {
        "hex": "#312E2C",
        "share": 0.1334,
        "role": "ground",
        "chroma": 2,
        "lightness": 19.2
      }
    ],
    "image": {
      "commonsFile": "File:Vincent Willem van Gogh - Cafe Terrace at Night (Yorck).jpg",
      "commonsPage": "https://commons.wikimedia.org/wiki/File:Vincent_Willem_van_Gogh_-_Cafe_Terrace_at_Night_(Yorck).jpg",
      "license": "Public domain"
    }
  },
  {
    "slug": "a-sunday-on-la-grande-jatte",
    "title": "A Sunday on La Grande Jatte",
    "artist": "Georges Seurat",
    "year": "1884–86",
    "museum": "Art Institute of Chicago",
    "summary": "A palette that has demonstrably changed since it was painted — and was already changing while Seurat was alive.",
    "story": [
      "Seurat built this surface from small separate touches of colour intended to mix in the eye rather than on the palette. The extracted swatches therefore read as averages of many adjacent dots, which is closer to how the painting actually looks from across a room than any single brushstroke would be.",
      "What makes this canvas unusual in a colour collection is that we know it has shifted, and roughly by how much. Some of the yellow-green passages have darkened toward ochre, changing the balance of the whole composition."
    ],
    "pigments": [
      {
        "name": "Zinc yellow (zinc potassium chromate, K₂O·4ZnCrO₄·3H₂O)",
        "note": "Used in the bright yellow-green passages. Chemically unstable."
      },
      {
        "name": "Emerald green, vermilion, cobalt blue and other modern pigments",
        "note": "Seurat worked from the newly-available industrial palette of the 1880s."
      }
    ],
    "shift": "Substantially, and early. Darkening of specific brushstrokes was recorded as soon as 1892 — six years after completion. Zinc yellow moves from bright greenish-yellow toward dull ochre as Cr(VI) reduces to Cr(III); artificial ageing reproduced the effect most strongly under strong light, high humidity and sulfur dioxide. The Art Institute of Chicago and the Rochester Institute of Technology have since produced digital reconstructions of the original colour.",
    "sources": [
      {
        "label": "Electron energy loss spectroscopy and the darkening of zinc potassium chromate in La Grande Jatte — Anal. Bioanal. Chem.",
        "href": "https://link.springer.com/article/10.1007/s00216-010-4264-9"
      },
      {
        "label": "ColourLex — Georges Seurat, A Sunday on La Grande Jatte",
        "href": "https://colourlex.com/project/georges-seurat-a-sunday-on-la-grande-jatte/"
      }
    ],
    "colors": [
      {
        "hex": "#BEB356",
        "share": 0.0546,
        "role": "accent",
        "chroma": 48.9,
        "lightness": 72.1
      },
      {
        "hex": "#B88862",
        "share": 0.0179,
        "role": "accent",
        "chroma": 30.7,
        "lightness": 60.5
      },
      {
        "hex": "#AB594B",
        "share": 0.0146,
        "role": "accent",
        "chroma": 39.6,
        "lightness": 47.4
      },
      {
        "hex": "#50526E",
        "share": 0.0549,
        "role": "ground",
        "chroma": 17.4,
        "lightness": 35.7
      },
      {
        "hex": "#3F3D49",
        "share": 0.0655,
        "role": "ground",
        "chroma": 7.9,
        "lightness": 26.4
      },
      {
        "hex": "#304235",
        "share": 0.0775,
        "role": "ground",
        "chroma": 11.8,
        "lightness": 26.1
      }
    ],
    "image": {
      "commonsFile": "File:A Sunday on La Grande Jatte, Georges Seurat, 1884.jpg",
      "commonsPage": "https://commons.wikimedia.org/wiki/File:A_Sunday_on_La_Grande_Jatte,_Georges_Seurat,_1884.jpg",
      "license": "Public domain"
    }
  },
  {
    "slug": "the-great-wave-off-kanagawa",
    "title": "Under the Wave off Kanagawa (The Great Wave)",
    "artist": "Katsushika Hokusai",
    "year": "c. 1831",
    "museum": "Multiple impressions; Metropolitan Museum of Art and others",
    "summary": "Cream paper, three blues, and one imported chemical that changed Japanese printmaking.",
    "story": [
      "The palette is startlingly economical: the warm cream of the paper carries most of the surface, and the entire drama comes from a narrow band of blues. There is no green, no red, no yellow accent. A designer copying this scheme gets a lesson in how far a single hue family plus a warm neutral can go.",
      "The blue itself is the historical event. Prussian blue was a European laboratory accident from around 1704–06 in Berlin, and it reached Japan through Dutch traders at Nagasaki. It was far too expensive for print runs until Chinese production made it affordable in the late 1820s — which is precisely when this series appeared."
    ],
    "pigments": [
      {
        "name": "Prussian blue (bero-ai / ベロ藍)",
        "note": "The dominant blue. Named for Berlin, its city of origin, shortened in Japanese from 'Berlin indigo'."
      },
      {
        "name": "Traditional indigo and plant colourants",
        "note": "Used alongside the imported blue in ukiyo-e printing of this period."
      }
    ],
    "shift": "This is a woodblock print, not a painting, so surviving impressions differ from one another as much as from the original — inking varied between pulls, and many sheets have faded unevenly with light exposure. Treat these values as one impression's reading rather than a single definitive palette.",
    "sources": [
      {
        "label": "MFA CAMEO — Prussian Blue as ukiyo-e colorant",
        "href": "https://cameo.mfa.org/wiki/Category:Prussian_Blue:_Ukiyo-e_colorant"
      },
      {
        "label": "JAANUS — berorin-ai (ベロリン藍)",
        "href": "https://projects.mcah.columbia.edu/jaanus/node/5118"
      }
    ],
    "colors": [
      {
        "hex": "#F6EFD9",
        "share": 0.34,
        "role": "ground",
        "chroma": 11.6,
        "lightness": 94.5
      },
      {
        "hex": "#F8EAC7",
        "share": 0.1733,
        "role": "ground",
        "chroma": 18.7,
        "lightness": 93
      },
      {
        "hex": "#DCE7D9",
        "share": 0.0546,
        "role": "ground",
        "chroma": 8.3,
        "lightness": 90.5
      },
      {
        "hex": "#E5B696",
        "share": 0.0073,
        "role": "accent",
        "chroma": 26,
        "lightness": 77.5
      },
      {
        "hex": "#2C638C",
        "share": 0.0247,
        "role": "accent",
        "chroma": 28.3,
        "lightness": 40.2
      },
      {
        "hex": "#223F63",
        "share": 0.0325,
        "role": "accent",
        "chroma": 24.6,
        "lightness": 26.1
      }
    ],
    "image": {
      "commonsFile": "File:Tsunami by hokusai 19th century.jpg",
      "commonsPage": "https://commons.wikimedia.org/wiki/File:Tsunami_by_hokusai_19th_century.jpg",
      "license": "Public domain"
    }
  },
  {
    "slug": "water-lilies",
    "title": "Water Lilies",
    "artist": "Claude Monet",
    "year": "1906",
    "museum": "Art Institute of Chicago",
    "summary": "A 6-colour reading of Water Lilies, sampled from the canvas itself.",
    "story": [
      "This palette runs from #A77E79 at its lightest to #4A6F8D at its darkest, with 3 accent notes carrying most of the chromatic interest. The three largest areas of the painting set the base; the accents are the colours that give the work its character without necessarily covering much of it.",
      "Every swatch is a colour that genuinely occurs on the surface — each one is snapped to the nearest real pixel rather than averaged, so nothing here is a colour the painter never actually put down."
    ],
    "pigments": [],
    "shift": null,
    "sources": [],
    "colors": [
      {
        "hex": "#A77E79",
        "share": 0.0038,
        "role": "accent",
        "chroma": 17.5,
        "lightness": 56.6
      },
      {
        "hex": "#5F935C",
        "share": 0.0098,
        "role": "accent",
        "chroma": 37.4,
        "lightness": 56.2
      },
      {
        "hex": "#5086A6",
        "share": 0.0708,
        "role": "ground",
        "chroma": 24.1,
        "lightness": 53.5
      },
      {
        "hex": "#547987",
        "share": 0.0654,
        "role": "ground",
        "chroma": 15,
        "lightness": 48.6
      },
      {
        "hex": "#696E8F",
        "share": 0.0337,
        "role": "accent",
        "chroma": 19.6,
        "lightness": 47.2
      },
      {
        "hex": "#4A6F8D",
        "share": 0.0666,
        "role": "ground",
        "chroma": 21,
        "lightness": 45.3
      }
    ],
    "image": {
      "commonsFile": "File:Claude Monet - Water Lilies - 1906, Ryerson.jpg",
      "commonsPage": "https://commons.wikimedia.org/wiki/File:Claude_Monet_-_Water_Lilies_-_1906,_Ryerson.jpg",
      "license": "Public domain"
    }
  },
  {
    "slug": "impression-sunrise",
    "title": "Impression, Sunrise",
    "artist": "Claude Monet",
    "year": "1872",
    "museum": "Musée Marmottan Monet, Paris",
    "summary": "A grey-green harbour, and a sun that occupies almost none of the canvas while defining all of it.",
    "story": [
      "Monet's sun is small, and the rest of the painting is a muted field of blue-greys and sage. The orange is nonetheless the reason anyone remembers the picture. Measured strictly by surface area it barely registers; measured by attention it is the entire composition.",
      "For designers this is the most directly transferable lesson in the collection: a single saturated accent, used at perhaps two percent of the surface, against a large desaturated field, will carry a layout. Most palettes fail by making the accent too big."
    ],
    "pigments": [],
    "shift": null,
    "sources": [],
    "colors": [
      {
        "hex": "#7E7D6A",
        "share": 0.0641,
        "role": "ground",
        "chroma": 11,
        "lightness": 52
      },
      {
        "hex": "#6C7A65",
        "share": 0.0552,
        "role": "accent",
        "chroma": 13.6,
        "lightness": 49.6
      },
      {
        "hex": "#6E7168",
        "share": 0.1106,
        "role": "ground",
        "chroma": 5.5,
        "lightness": 47.1
      },
      {
        "hex": "#B64E39",
        "share": 0.0011,
        "role": "accent",
        "chroma": 52.5,
        "lightness": 46.6
      },
      {
        "hex": "#5E7167",
        "share": 0.0647,
        "role": "ground",
        "chroma": 9.8,
        "lightness": 45.9
      },
      {
        "hex": "#5E665D",
        "share": 0.046,
        "role": "accent",
        "chroma": 6.4,
        "lightness": 42.3
      }
    ],
    "image": {
      "commonsFile": "File:Monet - Impression, Sunrise.jpg",
      "commonsPage": "https://commons.wikimedia.org/wiki/File:Monet_-_Impression,_Sunrise.jpg",
      "license": "Public domain"
    }
  },
  {
    "slug": "paris-street-rainy-day",
    "title": "Paris Street; Rainy Day",
    "artist": "Gustave Caillebotte",
    "year": "1877",
    "museum": "Art Institute of Chicago",
    "summary": "A 6-colour reading of Paris Street; Rainy Day, sampled from the canvas itself.",
    "story": [
      "This palette runs from #E6DDC1 at its lightest to #38342A at its darkest, with 3 accent notes carrying most of the chromatic interest. The three largest areas of the painting set the base; the accents are the colours that give the work its character without necessarily covering much of it.",
      "Every swatch is a colour that genuinely occurs on the surface — each one is snapped to the nearest real pixel rather than averaged, so nothing here is a colour the painter never actually put down."
    ],
    "pigments": [],
    "shift": null,
    "sources": [],
    "colors": [
      {
        "hex": "#E6DDC1",
        "share": 0.1308,
        "role": "ground",
        "chroma": 14.9,
        "lightness": 88.2
      },
      {
        "hex": "#CACABC",
        "share": 0.072,
        "role": "ground",
        "chroma": 7.4,
        "lightness": 81
      },
      {
        "hex": "#B2AFA4",
        "share": 0.0645,
        "role": "accent",
        "chroma": 6.1,
        "lightness": 71.4
      },
      {
        "hex": "#A4796D",
        "share": 0.0241,
        "role": "accent",
        "chroma": 20,
        "lightness": 54.7
      },
      {
        "hex": "#385B51",
        "share": 0.0096,
        "role": "accent",
        "chroma": 15.3,
        "lightness": 35.8
      },
      {
        "hex": "#38342A",
        "share": 0.0866,
        "role": "ground",
        "chroma": 7,
        "lightness": 21.8
      }
    ],
    "image": {
      "commonsFile": "File:Gustave Caillebotte - Paris Street; Rainy Day - Google Art Project.jpg",
      "commonsPage": "https://commons.wikimedia.org/wiki/File:Gustave_Caillebotte_-_Paris_Street;_Rainy_Day_-_Google_Art_Project.jpg",
      "license": "Public domain"
    }
  },
  {
    "slug": "the-kiss",
    "title": "The Kiss",
    "artist": "Gustav Klimt",
    "year": "1907–08",
    "museum": "Belvedere, Vienna",
    "summary": "The most famous gold in painting is mostly not gold, and none of it is a pigment.",
    "story": [
      "Every swatch here is an approximation of something a hex code cannot really hold. The golds in this painting are metal leaf, not paint: they change with viewing angle and lighting in a way flat colour cannot reproduce. What the extraction can tell you is the colour the leaf reads as under gallery light, which is genuinely useful if you are designing something that has to sit beside a reproduction.",
      "The green, orange and violet notes come from the ornamental patterning in the robes, and they are what stop the scheme collapsing into a single metallic hue. Those small chromatic interruptions are the reason the painting reads as rich rather than merely shiny."
    ],
    "pigments": [
      {
        "name": "Gold, silver and platinum leaf",
        "note": "Within the figures."
      },
      {
        "name": "Brass imitation gold ('composition gold')",
        "note": "The background. Actual fine-gold content across the work amounts to only grams."
      },
      {
        "name": "Oil paint",
        "note": "Flesh, foliage and the patterned colour notes."
      }
    ],
    "shift": "Cross-sections show Klimt laying leaf directly onto a still-tacky resin-bound imprimatur, without the traditional oil mordant used in classical gilding — timing the application to the tack of the layer beneath so that gilding became part of the painting process rather than a step after it. Metal leaf does not fade the way organic pigments do, but it does tarnish and abrade selectively.",
    "sources": [
      {
        "label": "The Kiss (Klimt) — materials and Belvedere documentation",
        "href": "https://en.wikipedia.org/wiki/The_Kiss_(Klimt)"
      }
    ],
    "colors": [
      {
        "hex": "#C3A749",
        "share": 0.0893,
        "role": "ground",
        "chroma": 51.2,
        "lightness": 69.3
      },
      {
        "hex": "#66893E",
        "share": 0.0197,
        "role": "accent",
        "chroma": 44,
        "lightness": 53
      },
      {
        "hex": "#8B7740",
        "share": 0.0931,
        "role": "ground",
        "chroma": 32.8,
        "lightness": 50.7
      },
      {
        "hex": "#BA5932",
        "share": 0.0044,
        "role": "accent",
        "chroma": 54.2,
        "lightness": 49.3
      },
      {
        "hex": "#7A642D",
        "share": 0.0834,
        "role": "ground",
        "chroma": 33.9,
        "lightness": 43.4
      },
      {
        "hex": "#6156A3",
        "share": 0.0079,
        "role": "accent",
        "chroma": 46.8,
        "lightness": 41
      }
    ],
    "image": {
      "commonsFile": "File:The Kiss - Gustav Klimt - Google Cultural Institute.jpg",
      "commonsPage": "https://commons.wikimedia.org/wiki/File:The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg",
      "license": "Public domain"
    }
  },
  {
    "slug": "the-scream",
    "title": "The Scream",
    "artist": "Edvard Munch",
    "year": "1893",
    "museum": "National Gallery, Oslo",
    "summary": "Oranges and scorched reds over a bruised ground — and yellows that are quietly turning white.",
    "story": [
      "The scheme is almost entirely warm, and its power comes from value rather than hue contrast: mid-toned oranges sit against browns of similar saturation, so nothing in the picture offers the eye a place to rest. Used in design, this palette produces the same low-level unease, which is worth knowing before applying it to anything that needs to feel calm.",
      "Munch made several versions in different media. The swatches here read one of them, so expect real variation against other reproductions you may have seen."
    ],
    "pigments": [
      {
        "name": "Cadmium yellow (cadmium sulfide, CdS)",
        "note": "Used thickly in the sky and water. Degrading."
      },
      {
        "name": "Cadmium-based oranges and reds",
        "note": "The sky bands."
      }
    ],
    "shift": "Yes, and against the usual assumption. In the c. 1910 version, some cadmium yellow strokes in the sky and the figure's neck have turned off-white, and thickly-painted water is flaking. Synchrotron work found that moisture, not light, is the main driver: chloride compounds at high humidity oxidise cadmium sulfide to cadmium sulfate. The museum's guidance is to hold the work below 45% relative humidity.",
    "sources": [
      {
        "label": "Probing the chemistry of CdS paints in The Scream — Science Advances",
        "href": "https://www.science.org/doi/10.1126/sciadv.aay3514"
      },
      {
        "label": "Munchmuseet — why The Scream is fading",
        "href": "https://www.munch.no/en/about/conservation/researchers-have-found-out-why-the-scream-is-fading/"
      }
    ],
    "colors": [
      {
        "hex": "#B27432",
        "share": 0.0222,
        "role": "accent",
        "chroma": 48.7,
        "lightness": 54.2
      },
      {
        "hex": "#866B52",
        "share": 0.0712,
        "role": "ground",
        "chroma": 19.4,
        "lightness": 47.2
      },
      {
        "hex": "#796757",
        "share": 0.072,
        "role": "ground",
        "chroma": 12.5,
        "lightness": 44.9
      },
      {
        "hex": "#A24F39",
        "share": 0.0357,
        "role": "accent",
        "chroma": 43.4,
        "lightness": 43.6
      },
      {
        "hex": "#A84530",
        "share": 0.0219,
        "role": "accent",
        "chroma": 51.3,
        "lightness": 42.5
      },
      {
        "hex": "#695B52",
        "share": 0.0683,
        "role": "ground",
        "chroma": 8.3,
        "lightness": 39.7
      }
    ],
    "image": {
      "commonsFile": "File:Edvard Munch, 1893, The Scream, oil, tempera and pastel on cardboard, 91 x 73 cm, National Gallery of Norway.jpg",
      "commonsPage": "https://commons.wikimedia.org/wiki/File:Edvard_Munch,_1893,_The_Scream,_oil,_tempera_and_pastel_on_cardboard,_91_x_73_cm,_National_Gallery_of_Norway.jpg",
      "license": "Public domain"
    }
  },
  {
    "slug": "girl-with-a-pearl-earring",
    "title": "Girl with a Pearl Earring",
    "artist": "Johannes Vermeer",
    "year": "c. 1665",
    "museum": "Mauritshuis, The Hague",
    "summary": "A warm, almost monochrome ground interrupted by one blue that cost more than gold.",
    "story": [
      "Nearly the whole surface is warm: skin, ochre jacket, and a background so dark it reads as near-black. The blue of the headscarf occupies very little of the canvas, and it is the only cool note in the scheme. That imbalance is the design lesson — a single small cool accent against a large warm field will always dominate attention, regardless of how little space it occupies.",
      "The blue is natural ultramarine, ground from lapis lazuli mined in what is now Afghanistan. In the seventeenth century the prepared pigment was more valuable than gold by weight, which makes its use on a scarf rather than a Virgin's robe a genuinely extravagant choice."
    ],
    "pigments": [
      {
        "name": "Natural ultramarine (lazurite, from lapis lazuli)",
        "note": "The headscarf. Analysis found a high proportion of bright lazurite particles — a high-quality grade."
      },
      {
        "name": "Lead white, ochres and earths",
        "note": "The flesh tones and jacket."
      }
    ],
    "shift": "The Girl in the Spotlight project (2018) examined the painting with SEM-EDX, FTIR-ATR and synchrotron sulfur K-edge XANES. One finding was that the lapis appears to have been heat-treated before grinding, which made the stone easier to work and yielded a more intense blue. Ultramarine is chemically stable, so this blue is close to what Vermeer laid down.",
    "sources": [
      {
        "label": "Out of the blue: Vermeer's use of ultramarine in Girl with a Pearl Earring — npj Heritage Science",
        "href": "https://www.nature.com/articles/s40494-020-00364-5"
      },
      {
        "label": "Mauritshuis — Closer to Vermeer and the Girl",
        "href": "https://www.mauritshuis.nl/en/our-collection/restoration-and-research/closer-to-vermeer-and-the-girl"
      }
    ],
    "colors": [
      {
        "hex": "#CDA264",
        "share": 0.0171,
        "role": "accent",
        "chroma": 39,
        "lightness": 69.3
      },
      {
        "hex": "#A66452",
        "share": 0.0021,
        "role": "accent",
        "chroma": 32.7,
        "lightness": 49.3
      },
      {
        "hex": "#587893",
        "share": 0.0053,
        "role": "accent",
        "chroma": 18.7,
        "lightness": 49
      },
      {
        "hex": "#332E23",
        "share": 0.0756,
        "role": "ground",
        "chroma": 7.9,
        "lightness": 19.1
      },
      {
        "hex": "#26231F",
        "share": 0.0515,
        "role": "ground",
        "chroma": 3.2,
        "lightness": 13.9
      },
      {
        "hex": "#231B0E",
        "share": 0.4782,
        "role": "ground",
        "chroma": 9.7,
        "lightness": 10.4
      }
    ],
    "image": {
      "commonsFile": "File:1665 Girl with a Pearl Earring.jpg",
      "commonsPage": "https://commons.wikimedia.org/wiki/File:1665_Girl_with_a_Pearl_Earring.jpg",
      "license": "Public domain"
    }
  },
  {
    "slug": "the-birth-of-venus",
    "title": "The Birth of Venus",
    "artist": "Sandro Botticelli",
    "year": "c. 1485",
    "museum": "Uffizi Gallery, Florence",
    "summary": "A 6-colour reading of The Birth of Venus, sampled from the canvas itself.",
    "story": [
      "This palette runs from #E3E0CE at its lightest to #343023 at its darkest, with 3 accent notes carrying most of the chromatic interest. The three largest areas of the painting set the base; the accents are the colours that give the work its character without necessarily covering much of it.",
      "Every swatch is a colour that genuinely occurs on the surface — each one is snapped to the nearest real pixel rather than averaged, so nothing here is a colour the painter never actually put down."
    ],
    "pigments": [],
    "shift": null,
    "sources": [],
    "colors": [
      {
        "hex": "#E3E0CE",
        "share": 0.0703,
        "role": "ground",
        "chroma": 9.4,
        "lightness": 89
      },
      {
        "hex": "#CDCBAB",
        "share": 0.0786,
        "role": "ground",
        "chroma": 16.9,
        "lightness": 81.1
      },
      {
        "hex": "#D7B051",
        "share": 0.0137,
        "role": "accent",
        "chroma": 52.9,
        "lightness": 73.6
      },
      {
        "hex": "#C98A2F",
        "share": 0.0108,
        "role": "accent",
        "chroma": 57.8,
        "lightness": 62.3
      },
      {
        "hex": "#8A4B31",
        "share": 0.0221,
        "role": "accent",
        "chroma": 36.2,
        "lightness": 39
      },
      {
        "hex": "#343023",
        "share": 0.0625,
        "role": "ground",
        "chroma": 9,
        "lightness": 19.9
      }
    ],
    "image": {
      "commonsFile": "File:Sandro Botticelli - La nascita di Venere - Google Art Project - edited.jpg",
      "commonsPage": "https://commons.wikimedia.org/wiki/File:Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg",
      "license": "Public domain"
    }
  },
  {
    "slug": "the-night-watch",
    "title": "The Night Watch",
    "artist": "Rembrandt van Rijn",
    "year": "1642",
    "museum": "Rijksmuseum, Amsterdam",
    "summary": "A 6-colour reading of The Night Watch, sampled from the canvas itself.",
    "story": [
      "This palette runs from #84673B at its lightest to #16120E at its darkest, with 3 accent notes carrying most of the chromatic interest. The three largest areas of the painting set the base; the accents are the colours that give the work its character without necessarily covering much of it.",
      "Every swatch is a colour that genuinely occurs on the surface — each one is snapped to the nearest real pixel rather than averaged, so nothing here is a colour the painter never actually put down."
    ],
    "pigments": [],
    "shift": null,
    "sources": [],
    "colors": [
      {
        "hex": "#84673B",
        "share": 0.0145,
        "role": "accent",
        "chroma": 29.7,
        "lightness": 45.5
      },
      {
        "hex": "#70532B",
        "share": 0.0158,
        "role": "accent",
        "chroma": 28.7,
        "lightness": 37.5
      },
      {
        "hex": "#65341A",
        "share": 0.0038,
        "role": "accent",
        "chroma": 32.3,
        "lightness": 27.6
      },
      {
        "hex": "#302313",
        "share": 0.1789,
        "role": "ground",
        "chroma": 13.5,
        "lightness": 14.8
      },
      {
        "hex": "#221910",
        "share": 0.2704,
        "role": "ground",
        "chroma": 7.9,
        "lightness": 9.6
      },
      {
        "hex": "#16120E",
        "share": 0.2694,
        "role": "ground",
        "chroma": 2.8,
        "lightness": 5.7
      }
    ],
    "image": {
      "commonsFile": "File:The Night Watch - HD.jpg",
      "commonsPage": "https://commons.wikimedia.org/wiki/File:The_Night_Watch_-_HD.jpg",
      "license": "Public domain"
    }
  },
  {
    "slug": "at-the-moulin-rouge",
    "title": "At the Moulin Rouge",
    "artist": "Henri de Toulouse-Lautrec",
    "year": "1892–95",
    "museum": "Art Institute of Chicago",
    "summary": "A 6-colour reading of At the Moulin Rouge, sampled from the canvas itself.",
    "story": [
      "This palette runs from #836612 at its lightest to #26241E at its darkest, with 3 accent notes carrying most of the chromatic interest. The three largest areas of the painting set the base; the accents are the colours that give the work its character without necessarily covering much of it.",
      "Every swatch is a colour that genuinely occurs on the surface — each one is snapped to the nearest real pixel rather than averaged, so nothing here is a colour the painter never actually put down."
    ],
    "pigments": [],
    "shift": null,
    "sources": [],
    "colors": [
      {
        "hex": "#836612",
        "share": 0.0081,
        "role": "accent",
        "chroma": 47.3,
        "lightness": 44.8
      },
      {
        "hex": "#505932",
        "share": 0.0251,
        "role": "accent",
        "chroma": 23.9,
        "lightness": 36.1
      },
      {
        "hex": "#66440A",
        "share": 0.0311,
        "role": "accent",
        "chroma": 38.6,
        "lightness": 31.8
      },
      {
        "hex": "#5C3B0C",
        "share": 0.0959,
        "role": "ground",
        "chroma": 34.4,
        "lightness": 27.9
      },
      {
        "hex": "#2D281B",
        "share": 0.0928,
        "role": "ground",
        "chroma": 9.4,
        "lightness": 16.3
      },
      {
        "hex": "#26241E",
        "share": 0.135,
        "role": "ground",
        "chroma": 4.4,
        "lightness": 14.2
      }
    ],
    "image": {
      "commonsFile": "File:Henri de Toulouse-Lautrec - At the Moulin Rouge - Google Art Project.jpg",
      "commonsPage": "https://commons.wikimedia.org/wiki/File:Henri_de_Toulouse-Lautrec_-_At_the_Moulin_Rouge_-_Google_Art_Project.jpg",
      "license": "Public domain"
    }
  },
  {
    "slug": "the-childs-bath",
    "title": "The Child's Bath",
    "artist": "Mary Cassatt",
    "year": "1893",
    "museum": "Art Institute of Chicago",
    "summary": "A 6-colour reading of The Child's Bath, sampled from the canvas itself.",
    "story": [
      "This palette runs from #98A3AD at its lightest to #283B51 at its darkest, with 3 accent notes carrying most of the chromatic interest. The three largest areas of the painting set the base; the accents are the colours that give the work its character without necessarily covering much of it.",
      "Every swatch is a colour that genuinely occurs on the surface — each one is snapped to the nearest real pixel rather than averaged, so nothing here is a colour the painter never actually put down."
    ],
    "pigments": [],
    "shift": null,
    "sources": [],
    "colors": [
      {
        "hex": "#98A3AD",
        "share": 0.0692,
        "role": "ground",
        "chroma": 6.8,
        "lightness": 66.4
      },
      {
        "hex": "#56686F",
        "share": 0.0436,
        "role": "accent",
        "chroma": 8,
        "lightness": 42.8
      },
      {
        "hex": "#636449",
        "share": 0.0711,
        "role": "ground",
        "chroma": 16.1,
        "lightness": 41.6
      },
      {
        "hex": "#4C5345",
        "share": 0.0545,
        "role": "ground",
        "chroma": 9.3,
        "lightness": 34.3
      },
      {
        "hex": "#673928",
        "share": 0.0379,
        "role": "accent",
        "chroma": 26.8,
        "lightness": 29.3
      },
      {
        "hex": "#283B51",
        "share": 0.0233,
        "role": "accent",
        "chroma": 15.7,
        "lightness": 24.2
      }
    ],
    "image": {
      "commonsFile": "File:Mary Cassatt - The Child's Bath - Google Art Project.jpg",
      "commonsPage": "https://commons.wikimedia.org/wiki/File:Mary_Cassatt_-_The_Child%27s_Bath_-_Google_Art_Project.jpg",
      "license": "Public domain"
    }
  },
  {
    "slug": "two-sisters-on-the-terrace",
    "title": "Two Sisters (On the Terrace)",
    "artist": "Pierre-Auguste Renoir",
    "year": "1881",
    "museum": "Art Institute of Chicago",
    "summary": "A 6-colour reading of Two Sisters (On the Terrace), sampled from the canvas itself.",
    "story": [
      "This palette runs from #798483 at its lightest to #08467E at its darkest, with 3 accent notes carrying most of the chromatic interest. The three largest areas of the painting set the base; the accents are the colours that give the work its character without necessarily covering much of it.",
      "Every swatch is a colour that genuinely occurs on the surface — each one is snapped to the nearest real pixel rather than averaged, so nothing here is a colour the painter never actually put down."
    ],
    "pigments": [],
    "shift": null,
    "sources": [],
    "colors": [
      {
        "hex": "#798483",
        "share": 0.0676,
        "role": "ground",
        "chroma": 4.3,
        "lightness": 54.2
      },
      {
        "hex": "#77786A",
        "share": 0.0647,
        "role": "ground",
        "chroma": 8.2,
        "lightness": 50
      },
      {
        "hex": "#5C6261",
        "share": 0.0676,
        "role": "ground",
        "chroma": 2.6,
        "lightness": 41
      },
      {
        "hex": "#A03E23",
        "share": 0.0197,
        "role": "accent",
        "chroma": 53.6,
        "lightness": 39.7
      },
      {
        "hex": "#305651",
        "share": 0.0487,
        "role": "accent",
        "chroma": 15,
        "lightness": 33.7
      },
      {
        "hex": "#08467E",
        "share": 0.0073,
        "role": "accent",
        "chroma": 37,
        "lightness": 29.3
      }
    ],
    "image": {
      "commonsFile": "File:Pierre-Auguste Renoir - Two Sisters (On the Terrace) - Google Art Project.jpg",
      "commonsPage": "https://commons.wikimedia.org/wiki/File:Pierre-Auguste_Renoir_-_Two_Sisters_(On_the_Terrace)_-_Google_Art_Project.jpg",
      "license": "Public domain"
    }
  },
  {
    "slug": "the-fighting-temeraire",
    "title": "The Fighting Temeraire",
    "artist": "J. M. W. Turner",
    "year": "1839",
    "museum": "National Gallery, London",
    "summary": "A 6-colour reading of The Fighting Temeraire, sampled from the canvas itself.",
    "story": [
      "This palette runs from #AEA693 at its lightest to #825C33 at its darkest, with 3 accent notes carrying most of the chromatic interest. The three largest areas of the painting set the base; the accents are the colours that give the work its character without necessarily covering much of it.",
      "Every swatch is a colour that genuinely occurs on the surface — each one is snapped to the nearest real pixel rather than averaged, so nothing here is a colour the painter never actually put down."
    ],
    "pigments": [],
    "shift": null,
    "sources": [],
    "colors": [
      {
        "hex": "#AEA693",
        "share": 0.0607,
        "role": "ground",
        "chroma": 10.9,
        "lightness": 68.3
      },
      {
        "hex": "#909AA5",
        "share": 0.0314,
        "role": "accent",
        "chroma": 7.1,
        "lightness": 63.1
      },
      {
        "hex": "#918572",
        "share": 0.0803,
        "role": "ground",
        "chroma": 12,
        "lightness": 56.1
      },
      {
        "hex": "#938367",
        "share": 0.1465,
        "role": "ground",
        "chroma": 17.5,
        "lightness": 55.5
      },
      {
        "hex": "#96763E",
        "share": 0.0174,
        "role": "accent",
        "chroma": 35.7,
        "lightness": 51.6
      },
      {
        "hex": "#825C33",
        "share": 0.0197,
        "role": "accent",
        "chroma": 31.4,
        "lightness": 42.2
      }
    ],
    "image": {
      "commonsFile": "File:The Fighting Temeraire, JMW Turner, National Gallery.jpg",
      "commonsPage": "https://commons.wikimedia.org/wiki/File:The_Fighting_Temeraire,_JMW_Turner,_National_Gallery.jpg",
      "license": "Public domain"
    }
  },
  {
    "slug": "wanderer-above-the-sea-of-fog",
    "title": "Wanderer above the Sea of Fog",
    "artist": "Caspar David Friedrich",
    "year": "c. 1818",
    "museum": "Hamburger Kunsthalle",
    "summary": "A 6-colour reading of Wanderer above the Sea of Fog, sampled from the canvas itself.",
    "story": [
      "This palette runs from #CED3E4 at its lightest to #0E0C12 at its darkest, with 3 accent notes carrying most of the chromatic interest. The three largest areas of the painting set the base; the accents are the colours that give the work its character without necessarily covering much of it.",
      "Every swatch is a colour that genuinely occurs on the surface — each one is snapped to the nearest real pixel rather than averaged, so nothing here is a colour the painter never actually put down."
    ],
    "pigments": [],
    "shift": null,
    "sources": [],
    "colors": [
      {
        "hex": "#CED3E4",
        "share": 0.2364,
        "role": "ground",
        "chroma": 9.1,
        "lightness": 84.6
      },
      {
        "hex": "#BDC0CC",
        "share": 0.1958,
        "role": "ground",
        "chroma": 6.5,
        "lightness": 77.8
      },
      {
        "hex": "#939CA9",
        "share": 0.0313,
        "role": "accent",
        "chroma": 7.9,
        "lightness": 64
      },
      {
        "hex": "#8B7763",
        "share": 0.0022,
        "role": "accent",
        "chroma": 14.6,
        "lightness": 51.4
      },
      {
        "hex": "#64707B",
        "share": 0.0209,
        "role": "accent",
        "chroma": 7.8,
        "lightness": 46.6
      },
      {
        "hex": "#0E0C12",
        "share": 0.1723,
        "role": "ground",
        "chroma": 3.2,
        "lightness": 3.6
      }
    ],
    "image": {
      "commonsFile": "File:Caspar David Friedrich - Wanderer above the sea of fog.jpg",
      "commonsPage": "https://commons.wikimedia.org/wiki/File:Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg",
      "license": "Public domain"
    }
  },
  {
    "slug": "the-garden-of-earthly-delights",
    "title": "The Garden of Earthly Delights",
    "artist": "Hieronymus Bosch",
    "year": "c. 1500",
    "museum": "Museo del Prado, Madrid",
    "summary": "A 6-colour reading of The Garden of Earthly Delights, sampled from the canvas itself.",
    "story": [
      "This palette runs from #CFCFB2 at its lightest to #090806 at its darkest, with 3 accent notes carrying most of the chromatic interest. The three largest areas of the painting set the base; the accents are the colours that give the work its character without necessarily covering much of it.",
      "Every swatch is a colour that genuinely occurs on the surface — each one is snapped to the nearest real pixel rather than averaged, so nothing here is a colour the painter never actually put down."
    ],
    "pigments": [],
    "shift": null,
    "sources": [],
    "colors": [
      {
        "hex": "#CFCFB2",
        "share": 0.0644,
        "role": "ground",
        "chroma": 15.3,
        "lightness": 82.4
      },
      {
        "hex": "#ACA745",
        "share": 0.051,
        "role": "accent",
        "chroma": 51.2,
        "lightness": 67.2
      },
      {
        "hex": "#8B852A",
        "share": 0.0518,
        "role": "accent",
        "chroma": 48.5,
        "lightness": 54.5
      },
      {
        "hex": "#965020",
        "share": 0.0148,
        "role": "accent",
        "chroma": 47.2,
        "lightness": 41.7
      },
      {
        "hex": "#201E14",
        "share": 0.0622,
        "role": "ground",
        "chroma": 7.2,
        "lightness": 11.2
      },
      {
        "hex": "#090806",
        "share": 0.131,
        "role": "ground",
        "chroma": 0.8,
        "lightness": 2.2
      }
    ],
    "image": {
      "commonsFile": "File:The Garden of earthly delights.jpg",
      "commonsPage": "https://commons.wikimedia.org/wiki/File:The_Garden_of_earthly_delights.jpg",
      "license": "Public domain"
    }
  },
  {
    "slug": "the-hay-wain",
    "title": "The Hay Wain",
    "artist": "John Constable",
    "year": "1821",
    "museum": "National Gallery, London",
    "summary": "A 6-colour reading of The Hay Wain, sampled from the canvas itself.",
    "story": [
      "This palette runs from #768BAC at its lightest to #2F211D at its darkest, with 3 accent notes carrying most of the chromatic interest. The three largest areas of the painting set the base; the accents are the colours that give the work its character without necessarily covering much of it.",
      "Every swatch is a colour that genuinely occurs on the surface — each one is snapped to the nearest real pixel rather than averaged, so nothing here is a colour the painter never actually put down."
    ],
    "pigments": [],
    "shift": null,
    "sources": [],
    "colors": [
      {
        "hex": "#768BAC",
        "share": 0.0262,
        "role": "accent",
        "chroma": 19.8,
        "lightness": 57.4
      },
      {
        "hex": "#605E57",
        "share": 0.06,
        "role": "ground",
        "chroma": 4.3,
        "lightness": 39.9
      },
      {
        "hex": "#4C4939",
        "share": 0.0607,
        "role": "ground",
        "chroma": 10.2,
        "lightness": 30.9
      },
      {
        "hex": "#584127",
        "share": 0.0392,
        "role": "accent",
        "chroma": 20.7,
        "lightness": 29.4
      },
      {
        "hex": "#333524",
        "share": 0.0671,
        "role": "ground",
        "chroma": 11.3,
        "lightness": 21.5
      },
      {
        "hex": "#2F211D",
        "share": 0.0364,
        "role": "accent",
        "chroma": 8,
        "lightness": 14.3
      }
    ],
    "image": {
      "commonsFile": "File:John Constable The Hay Wain.jpg",
      "commonsPage": "https://commons.wikimedia.org/wiki/File:John_Constable_The_Hay_Wain.jpg",
      "license": "Public domain"
    }
  },
  {
    "slug": "the-milkmaid",
    "title": "The Milkmaid",
    "artist": "Johannes Vermeer",
    "year": "c. 1660",
    "museum": "Rijksmuseum, Amsterdam",
    "summary": "Warm domestic neutrals, and then a blue that stops the room.",
    "story": [
      "The bulk of this palette is cream, tan and shadow — the ordinary colours of a plain interior. Vermeer then places natural ultramarine, the most expensive pigment available to him, on a kitchen servant's apron. The extravagance is the point, and the resulting contrast is why the figure holds the space so completely.",
      "The structure is the same as Girl with a Pearl Earring: a broad warm field, one small cool accent, and an almost complete absence of mid-tone competition."
    ],
    "pigments": [
      {
        "name": "Natural ultramarine (from lapis lazuli)",
        "note": "The apron."
      },
      {
        "name": "Lead-tin yellow, ochres, lead white",
        "note": "The bodice, bread and wall."
      }
    ],
    "shift": null,
    "sources": [
      {
        "label": "Vermeer's Palette: Natural Ultramarine — Essential Vermeer",
        "href": "https://www.essentialvermeer.com/palette/palette_ultramarine.html"
      }
    ],
    "colors": [
      {
        "hex": "#D7D1BF",
        "share": 0.1919,
        "role": "ground",
        "chroma": 9.7,
        "lightness": 83.9
      },
      {
        "hex": "#C6BDA9",
        "share": 0.0754,
        "role": "ground",
        "chroma": 11.2,
        "lightness": 76.8
      },
      {
        "hex": "#C89D7A",
        "share": 0.0086,
        "role": "accent",
        "chroma": 26.9,
        "lightness": 67.9
      },
      {
        "hex": "#254D83",
        "share": 0.0064,
        "role": "accent",
        "chroma": 34.9,
        "lightness": 32.6
      },
      {
        "hex": "#3C1914",
        "share": 0.0236,
        "role": "accent",
        "chroma": 20.2,
        "lightness": 13.9
      },
      {
        "hex": "#0F1317",
        "share": 0.0825,
        "role": "ground",
        "chroma": 3.1,
        "lightness": 5.7
      }
    ],
    "image": {
      "commonsFile": "File:Johannes Vermeer - Het melkmeisje - Google Art Project.jpg",
      "commonsPage": "https://commons.wikimedia.org/wiki/File:Johannes_Vermeer_-_Het_melkmeisje_-_Google_Art_Project.jpg",
      "license": "Public domain"
    }
  },
  {
    "slug": "ophelia",
    "title": "Ophelia",
    "artist": "John Everett Millais",
    "year": "1851–52",
    "museum": "Tate Britain, London",
    "summary": "A 6-colour reading of Ophelia, sampled from the canvas itself.",
    "story": [
      "This palette runs from #9A9B39 at its lightest to #161413 at its darkest, with 3 accent notes carrying most of the chromatic interest. The three largest areas of the painting set the base; the accents are the colours that give the work its character without necessarily covering much of it.",
      "Every swatch is a colour that genuinely occurs on the surface — each one is snapped to the nearest real pixel rather than averaged, so nothing here is a colour the painter never actually put down."
    ],
    "pigments": [],
    "shift": null,
    "sources": [],
    "colors": [
      {
        "hex": "#9A9B39",
        "share": 0.0162,
        "role": "accent",
        "chroma": 51.3,
        "lightness": 62.2
      },
      {
        "hex": "#657E1E",
        "share": 0.0291,
        "role": "accent",
        "chroma": 51.6,
        "lightness": 49.2
      },
      {
        "hex": "#775B2C",
        "share": 0.0297,
        "role": "accent",
        "chroma": 31.6,
        "lightness": 40.6
      },
      {
        "hex": "#1B2419",
        "share": 0.0577,
        "role": "ground",
        "chroma": 9.1,
        "lightness": 13
      },
      {
        "hex": "#2A1D17",
        "share": 0.0686,
        "role": "ground",
        "chroma": 8.5,
        "lightness": 12.2
      },
      {
        "hex": "#161413",
        "share": 0.0777,
        "role": "ground",
        "chroma": 1.1,
        "lightness": 6.5
      }
    ],
    "image": {
      "commonsFile": "File:John Everett Millais - Ophelia - Google Art Project.jpg",
      "commonsPage": "https://commons.wikimedia.org/wiki/File:John_Everett_Millais_-_Ophelia_-_Google_Art_Project.jpg",
      "license": "Public domain"
    }
  },
  {
    "slug": "the-third-of-may-1808",
    "title": "The Third of May 1808",
    "artist": "Francisco Goya",
    "year": "1814",
    "museum": "Museo del Prado, Madrid",
    "summary": "A 6-colour reading of The Third of May 1808, sampled from the canvas itself.",
    "story": [
      "This palette runs from #BE9453 at its lightest to #1E1D1A at its darkest, with 3 accent notes carrying most of the chromatic interest. The three largest areas of the painting set the base; the accents are the colours that give the work its character without necessarily covering much of it.",
      "Every swatch is a colour that genuinely occurs on the surface — each one is snapped to the nearest real pixel rather than averaged, so nothing here is a colour the painter never actually put down."
    ],
    "pigments": [],
    "shift": null,
    "sources": [],
    "colors": [
      {
        "hex": "#BE9453",
        "share": 0.0104,
        "role": "accent",
        "chroma": 40.8,
        "lightness": 64
      },
      {
        "hex": "#AE8152",
        "share": 0.0235,
        "role": "accent",
        "chroma": 34.2,
        "lightness": 57.4
      },
      {
        "hex": "#855532",
        "share": 0.0132,
        "role": "accent",
        "chroma": 32.7,
        "lightness": 40.8
      },
      {
        "hex": "#332B20",
        "share": 0.0577,
        "role": "ground",
        "chroma": 8.7,
        "lightness": 18.1
      },
      {
        "hex": "#281E14",
        "share": 0.0517,
        "role": "ground",
        "chroma": 9.2,
        "lightness": 12.2
      },
      {
        "hex": "#1E1D1A",
        "share": 0.3009,
        "role": "ground",
        "chroma": 2.2,
        "lightness": 10.8
      }
    ],
    "image": {
      "commonsFile": "File:El Tres de Mayo, by Francisco de Goya, from Prado thin black margin.jpg",
      "commonsPage": "https://commons.wikimedia.org/wiki/File:El_Tres_de_Mayo,_by_Francisco_de_Goya,_from_Prado_thin_black_margin.jpg",
      "license": "Public domain"
    }
  },
  {
    "slug": "the-tower-of-babel",
    "title": "The Tower of Babel",
    "artist": "Pieter Bruegel the Elder",
    "year": "1563",
    "museum": "Kunsthistorisches Museum, Vienna",
    "summary": "A 6-colour reading of The Tower of Babel, sampled from the canvas itself.",
    "story": [
      "This palette runs from #EDE5CD at its lightest to #964921 at its darkest, with 3 accent notes carrying most of the chromatic interest. The three largest areas of the painting set the base; the accents are the colours that give the work its character without necessarily covering much of it.",
      "Every swatch is a colour that genuinely occurs on the surface — each one is snapped to the nearest real pixel rather than averaged, so nothing here is a colour the painter never actually put down."
    ],
    "pigments": [],
    "shift": null,
    "sources": [],
    "colors": [
      {
        "hex": "#EDE5CD",
        "share": 0.0755,
        "role": "ground",
        "chroma": 12.7,
        "lightness": 91
      },
      {
        "hex": "#D9D8CB",
        "share": 0.0789,
        "role": "ground",
        "chroma": 6.8,
        "lightness": 86.1
      },
      {
        "hex": "#C69B3E",
        "share": 0.013,
        "role": "accent",
        "chroma": 53.4,
        "lightness": 66.4
      },
      {
        "hex": "#BA6E3A",
        "share": 0.0205,
        "role": "accent",
        "chroma": 48.4,
        "lightness": 53.9
      },
      {
        "hex": "#7C8357",
        "share": 0.0575,
        "role": "ground",
        "chroma": 25.2,
        "lightness": 53.2
      },
      {
        "hex": "#964921",
        "share": 0.018,
        "role": "accent",
        "chroma": 47.8,
        "lightness": 40.2
      }
    ],
    "image": {
      "commonsFile": "File:Pieter Bruegel the Elder - The Tower of Babel (Vienna) - Google Art Project - edited.jpg",
      "commonsPage": "https://commons.wikimedia.org/wiki/File:Pieter_Bruegel_the_Elder_-_The_Tower_of_Babel_(Vienna)_-_Google_Art_Project_-_edited.jpg",
      "license": "Public domain"
    }
  }
];

export function allPaintings(): PaintingPalette[] {
  return paintingPalettes;
}

export function paintingBySlug(slug: string): PaintingPalette | undefined {
  return paintingPalettes.find((p) => p.slug === slug);
}

/** Paintings sharing the nearest dominant hue — used for on-page cross-links. */
export function relatedPaintings(p: PaintingPalette, limit = 3): PaintingPalette[] {
  const hue = (hex: string) => {
    const r = parseInt(hex.slice(1, 3), 16) / 255;
    const g = parseInt(hex.slice(3, 5), 16) / 255;
    const b = parseInt(hex.slice(5, 7), 16) / 255;
    const max = Math.max(r, g, b), min = Math.min(r, g, b);
    if (max === min) return 0;
    const d = max - min;
    let h = 0;
    if (max === r) h = ((g - b) / d) % 6;
    else if (max === g) h = (b - r) / d + 2;
    else h = (r - g) / d + 4;
    return (h * 60 + 360) % 360;
  };
  const gap = (a: number, b: number) => {
    const d = Math.abs(a - b) % 360;
    return Math.min(d, 360 - d);
  };
  const mine = hue(p.colors[0].hex);
  return paintingPalettes
    .filter((q) => q.slug !== p.slug)
    .map((q) => ({ q, d: gap(mine, hue(q.colors[0].hex)) }))
    .sort((a, b) => a.d - b.d)
    .slice(0, limit)
    .map((x) => x.q);
}
